version: '3.6'

services:
  restaurant_ylab:
    container_name: restaurant_ylab
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_MODE: 0
      POSTGRES_HOST: "postgres_ylab"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      REDIS_HOST: "redis_ylab"
    entrypoint: sh -c "alembic upgrade head && python3 -m app"
    volumes:
      - shared-volume:/app/generated_files
    ports:
      - "8000:8000"
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy

  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    networks:
      - ylab_network

  redis_ylab:
    container_name: redis_ylab
    image: redis:7.2.4-alpine
    environment:
      REDIS_PORT: "6379"
      REDIS_DATABASES: 16
    volumes:
      - redis-data:/root/redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - ylab_network

volumes:
  postgres-data:
  shared-volume:
  redis-data:

networks:
  ylab_network:
    name: ylab_network
