version: '3.6'

services:
  tests_restaurant_ylab:
    container_name: tests_restaurant_ylab
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TEST_MODE=1
      - POSTGRES_HOST=tests_postgres_ylab
      - POSTGRES_DB=${POSTGRES_DB}_test
      - REDIS_HOST=tests_redis_ylab
    entrypoint: sh -c "pytest tests/"
    volumes:
      - tests-shared-volume:/app/generated_files
    ports:
      - "8000:8000"
    networks:
      - tests_ylab_network
    depends_on:
      tests_postgres_ylab:
        condition: service_healthy

  tests_postgres_ylab:
    container_name: tests_postgres_ylab
    image: postgres:15.1-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}_test
    volumes:
      - tests-postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}_test"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - tests_ylab_network

  tests_redis_ylab:
    container_name: tests_redis_ylab
    image: redis:7.2.4-alpine
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - tests-redis-data:/var/lib/redis/data
      - tests-redis-config:/var/lib/redis/redis.conf
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - tests_ylab_network

volumes:
  tests-postgres-data:
  tests-shared-volume:
  tests-redis-data:
  tests-redis-config:

networks:
  tests_ylab_network:
    name: tests_ylab_network
